const {
  DEV_PORT,
  DEV_NEON_DB_URL,
  DEV_CLOUDINARY_CLOUD_NAME,
  DEV_CLOUDINARY_API_KEY,
  DEV_CLOUDINARY_API_SECRET,
} = process.env;

console.log("Running in development mode");

export default {
  PORT: DEV_PORT,
  NEON: DEV_NEON_DB_URL,
  CLOUDINARY_CLOUD_NAME: DEV_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: DEV_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: DEV_CLOUDINARY_API_SECRET,
};
