const {
  DEV_PORT,
  DEV_NEON_DB_URL,
  DEV_CLOUDINARY_CLOUD_NAME,
  DEV_CLOUDINARY_API_KEY,
  DEV_CLOUDINARY_API_SECRET,
  PAYSTACK_TEST_SECRET_KEY,
  PAYSTACK_TEST_PUBLIC_KEY,
  DEV_FRONTEND_URL,
  LUMIID_BASE_URL,
  LUMIID_DEV_SECRET_KEY,
} = process.env;

console.log("Running in development mode");

export default {
  PORT: DEV_PORT,
  NEON: DEV_NEON_DB_URL,
  CLOUDINARY_CLOUD_NAME: DEV_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: DEV_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: DEV_CLOUDINARY_API_SECRET,
  PAYSTACK_SECRET_KEY: PAYSTACK_TEST_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: PAYSTACK_TEST_PUBLIC_KEY,
  FRONTEND_URL: DEV_FRONTEND_URL,
  LUMIID_BASE_URL,
  LUMIID_SECRET_KEY: LUMIID_DEV_SECRET_KEY,
};
