const {
  PROD_PORT,
  PROD_NEON_DB_URL,
  PROD_CLOUDINARY_CLOUD_NAME,
  PROD_CLOUDINARY_API_KEY,
  PROD_CLOUDINARY_API_SECRET,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  FRONTEND_URL,
  LUMIID_BASE_URL,
  LUMIID_SECRET_KEY,
} = process.env;

console.log("Running in production mode");

export default {
  PORT: PROD_PORT,
  NEON: PROD_NEON_DB_URL,
  CLOUDINARY_CLOUD_NAME: PROD_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: PROD_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: PROD_CLOUDINARY_API_SECRET,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  FRONTEND_URL,
  LUMIID_BASE_URL,
  LUMIID_SECRET_KEY,
};
