const {
  PROD_PORT,
  PROD_NEON_DB_URL,
  PROD_CLOUDINARY_CLOUD_NAME,
  PROD_CLOUDINARY_API_KEY,
  PROD_CLOUDINARY_API_SECRET,
} = process.env;

console.log("Running in production mode");

export default {
  PORT: PROD_PORT,
  NEON: PROD_NEON_DB_URL,
  CLOUDINARY_CLOUD_NAME: PROD_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: PROD_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: PROD_CLOUDINARY_API_SECRET,
};
